name: Extract Zip File

on:
  push:
    branches:
      - main

jobs:
  extract-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract zip file
      run: |
        unzip /home/hjbrl/Downloads/wordpress-6.2.2.zip -d https://github.com/muradhasan443/wordpress/
